### ISSUE TITLE
test_datatype.TestDatatype failure on Fedora Rawhide ppc64le

### ISSUE THREAD

**Issue by opoplawski** [mpi4py/mpi4py#106]
```
+ mpiexec -np 1 python3 test/runtests.py -v --no-builddir
/builddir/build/BUILD/mpi4py-3.1.1/test/runtests.py:76: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import get_platform
[0@buildvm-ppc64le-08.iad2.fedoraproject.org] Python 3.10 (/usr/bin/python3)
[0@buildvm-ppc64le-08.iad2.fedoraproject.org] MPI 3.1 (Open MPI 4.1.1)
[0@buildvm-ppc64le-08.iad2.fedoraproject.org] mpi4py 3.1.1 (/builddir/build/BUILDROOT/mpi4py-3.1.1-1.fc36.ppc64le/usr/lib64/python3.10/site-packages/openmpi/mpi4py)
...
======================================================================
ERROR: testCreateF90ComplexDouble (test_datatype.TestDatatype)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/mpi4py-3.1.1/test/test_datatype.py", line 324, in testCreateF90ComplexDouble
    self.check_datatype(None, factory, *args)
  File "/builddir/build/BUILD/mpi4py-3.1.1/test/test_datatype.py", line 144, in check_datatype
    newtype = factory(*args)
  File "mpi4py/MPI/Datatype.pyx", line 352, in mpi4py.MPI.Datatype.Create_f90_complex
mpi4py.MPI.Exception: MPI_ERR_ARG: invalid argument of some other kind
======================================================================
ERROR: testCreateF90RealDouble (test_datatype.TestDatatype)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/mpi4py-3.1.1/test/test_datatype.py", line 306, in testCreateF90RealDouble
    self.check_datatype(None, factory, *args)
  File "/builddir/build/BUILD/mpi4py-3.1.1/test/test_datatype.py", line 144, in check_datatype
    newtype = factory(*args)
  File "mpi4py/MPI/Datatype.pyx", line 343, in mpi4py.MPI.Datatype.Create_f90_real
mpi4py.MPI.Exception: MPI_ERR_ARG: invalid argument of some other kind
----------------------------------------------------------------------
Ran 1385 tests in 73.838s
FAILED (errors=2, skipped=191)
```

**Comment by dalcinl** [comment]
This is most likely an issue in Open MPI. You should ask the Open MPI package maintainers to add their own tests, and eventually report issues upstream. 

@jsquyres Any idea about these failures? Do you have ppc64le builds in your CI infrastructure?

@opoplawski I would suggest to disable the tests for now with the decorator stanza I use elsewhere:

```python
@unittest.skipMPI('openmpi', arch == 'ppc64le')   # you need to set the value of `arch` in a global variable
def testCreateF90RealDouble(self):
    ...
```

**Comment by drew-parsons** [comment]
The testCreate* errors started with OpenMPI 4, see https://bitbucket.org/mpi4py/mpi4py/issues/127/test-failure-with-openmpi-on-ppc64le

Logged also for Debian at  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=948655 (Debian is just skipping these tests on ppc).

**Comment by opoplawski** [comment]
Thanks, just logging it here to keep it on the radar so to speak.  FWIW - openmpi's make check passes in Fedora's ppc64le build of openmpi so I'm guessing it doesn't have a test that exposes this.

**Comment by dalcinl** [comment]
@opoplawski If you agree on the fact that this issue is no mpi4py's fault, please let's close it. IMHO, the tracking and resolution should be handled elsewhere.
