### ISSUE TITLE
test_util_dtlib.TestUtilDTLib failure on Fedora Rawhide s390x

### ISSUE THREAD

**Issue by opoplawski** [mpi4py/mpi4py#107]
```
+ mpiexec -np 1 python3 test/runtests.py -v --no-builddir
/builddir/build/BUILD/mpi4py-3.1.1/test/runtests.py:76: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import get_platform
[0@buildvm-s390x-20.s390.fedoraproject.org] Python 3.10 (/usr/bin/python3)
[0@buildvm-s390x-20.s390.fedoraproject.org] MPI 3.1 (Open MPI 4.1.1)
[0@buildvm-s390x-20.s390.fedoraproject.org] mpi4py 3.1.1 (/builddir/build/BUILDROOT/mpi4py-3.1.1-1.fc36.s390x/usr/lib64/python3.10/site-packages/openmpi/mpi4py)
--------------------------------------------------------------------------
The OSC pt2pt component does not support MPI_THREAD_MULTIPLE in this release.
Workarounds are to run on a single node, or to use a system with an RDMA
capable network such as Infiniband.
--------------------------------------------------------------------------
...
======================================================================
FAIL: testStruct4 (test_util_dtlib.TestUtilDTLib) (typecode='g')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/mpi4py-3.1.1/test/test_util_dtlib.py", line 165, in testStruct4
    self.assertEqual(mt.extent, n*ex1)
AssertionError: 40 != 48
======================================================================
FAIL: testStruct4 (test_util_dtlib.TestUtilDTLib) (typecode='G')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/mpi4py-3.1.1/test/test_util_dtlib.py", line 165, in testStruct4
    self.assertEqual(mt.extent, n*ex1)
AssertionError: 72 != 80
----------------------------------------------------------------------
Ran 1385 tests in 33.029s
FAILED (failures=2, skipped=191)
```

**Comment by dalcinl** [comment]
Please patch with the following commit: 163fee9b8dc88f2e9d6f777decdf87c2aed3fecb.

**Comment by dalcinl** [comment]
@opoplawski Any update?

**Comment by dalcinl** [comment]
@opoplawski Any update? If you do not reply back, I'll assume this issue is solved and then I'll close it.
