### ISSUE TITLE
demo/compute-pi/cpi-rma.py fails with MPI_ERR_WIN: invalid window

### ISSUE THREAD

**Issue by jeffhammond** [mpi4py/mpi4py#146]
I am using mpi4py on MacOS (Apple Silicon) with Open-MPI 4.1.1_2 from Homebrew (`/opt/homebrew/Cellar/open-mpi/4.1.1_2`).

I do not think the OSC warning below is relevant, because I am running a single process.

```
% mpiexec -n 1 python3 -m mpi4py demo/compute-pi/cpi-rma.py
--------------------------------------------------------------------------
The OSC pt2pt component does not support MPI_THREAD_MULTIPLE in this release.
Workarounds are to run on a single node, or to use a system with an RDMA
capable network such as Infiniband.
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/homebrew/lib/python3.9/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/opt/homebrew/lib/python3.9/site-packages/mpi4py/run.py", line 198, in main
    run_command_line(args)
  File "/opt/homebrew/lib/python3.9/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "demo/compute-pi/cpi-rma.py", line 44, in <module>
    win_n  = MPI.Win.Create(n,  comm=MPI.COMM_WORLD)
  File "mpi4py/MPI/Win.pyx", line 77, in mpi4py.MPI.Win.Create
mpi4py.MPI.Exception: MPI_ERR_WIN: invalid window
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

**Comment by piyueh** [comment]
I think it's #34. Also, you can try to either disable threading or use other osc backend. I tried in #139 and found `ucx` and `rdma` are working.

**Comment by jeffhammond** [comment]
It's a Mac laptop and I have no desire to recompile everything for UCX but clearly this is Open-MPI stupidity.

The other option I found was to use Win_allocate instead.  It took a while to figure out how to do that with Numpy, but now I'm good.

**Comment by dalcinl** [comment]
You have a couple options:

1. `brew unlink openmpi` and `brew install mpich`, next `python -m pip cache remove mpi4py` and `python -m pip install mpi4py`.
2. If your code does not require MPI thread safety, just `export MPI4PY_RC_THREAD_LEVEL=single`. 

```
$ MPI4PY_RC_THREAD_LEVEL=single mpiexec -n 1 python -m mpi4py demo/compute-pi/cpi-rma.py
Enter the number of intervals: (0 quits) 10000
pi is approximately 3.1415926544231341, error is 0.0000000008333410
Enter the number of intervals: (0 quits) 0
```

PS: I believe Open MPI 5 will get rid of the pt2pt OSC component, and they will provide a new proper, thread-safe OSC component.
