### ISSUE TITLE
Installation error with `setuptools==60.1.0`

### ISSUE THREAD

**Issue by nzw0301** [mpi4py/mpi4py#157]
The latest `setuptools` has removed `get_versions` method according to [this PR](https://github.com/pypa/setuptools/pull/2963/files#diff-379cbf81eb666c24bdd780d16a9db7ce56d84a0740149641b9942524e25790d8L415-L422). But `mpi4py` uses this method for installation as follows: https://github.com/mpi4py/mpi4py/blob/499468c8d1af7746841bdc7ddc6c6aefe61be78a/conf/mpidistutils.py#L32-L33

As a result, I saw the following error when I tries installing `mpi4py`

```bash
#9 49.81   Traceback (most recent call last):
#9 49.81     File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
#9 49.81       main()
#9 49.81     File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
#9 49.81       json_out['return_val'] = hook(**hook_input['kwargs'])
#9 49.81     File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
#9 49.81       return hook(config_settings)
#9 49.81     File "/tmp/pip-build-env-24728uki/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 163, in get_requires_for_build_wheel
#9 49.81       config_settings, requirements=['wheel'])
#9 49.81     File "/tmp/pip-build-env-24728uki/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
#9 49.81       self.run_setup()
#9 49.81     File "/tmp/pip-build-env-24728uki/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 158, in run_setup
#9 49.81       exec(compile(code, __file__, 'exec'), locals())
#9 49.81     File "setup.py", line 462, in <module>
#9 49.81       from mpidistutils import setup
#9 49.81     File "/tmp/pip-install-e88xwuui/mpi4py_a99d99dc8e2b489fbd0a8152611b34c3/conf/mpidistutils.py", line 29, in <module>
#9 49.81       cygcc_get_versions = cygcc.get_versions
#9 49.81   AttributeError: module 'setuptools._distutils.cygwinccompiler' has no attribute 'get_versions'
```

More detailed installation procedure is found in https://github.com/optuna/optuna/runs/4625423583?check_suite_focus=true.

**Comment by dalcinl** [comment]
If setuptools will keep breaking APIs, I'll have a hard time keeping things up to date.

**Comment by dalcinl** [comment]
Closed via #159.

@nzw0301 Thanks for the report!

**Comment by nzw0301** [comment]
My pleasure! Thank you so much for your quick fix!

**Comment by dalcinl** [comment]
# Workaround

```
export SETUPTOOLS_USE_DISTUTILS=stdlib
pip install mpi4py
```

**Comment by nzw0301** [comment]
I tried installing `mpi4py` using the workaround: 

```bash
SETUPTOOLS_USE_DISTUTILS=stdlib pip install -r requirements.txt
```

where `requirements.txt` contains `mpi4py`. The installation was completed successfully with the latest `setuptools==60.1.0`. Thank you for sharing it!

**Comment by aced125** [comment]
can we have a release for this please?

**Comment by dalcinl** [comment]
# Resolution

- pypa/setuptools#2969
- pypa/setuptools#2987
