### ISSUE TITLE
PyTorch 1.13 dlpack_is_contig fails

### ISSUE THREAD

**Issue by jmerizia** [mpi4py/mpi4py#274]
Hello! In the most recent update to PyTorch stable (1.13, and in nightly), I get this error with any collective operation on a tensor with >= 3 dimensions and a leading dimension size of 1 (CPU or CUDA).

```python
# python test.py

from mpi4py import MPI
import torch

x = torch.ones([1, 2, 2])
assert x.is_contiguous()
MPI.COMM_WORLD.Bcast(x)
```

```
Traceback (most recent call last):
  File "mpi4py/MPI/asbuffer.pxi", line 140, in mpi4py.MPI.PyMPI_GetBuffer
TypeError: a bytes-like object is required, not 'Tensor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    MPI.COMM_WORLD.Bcast(x)
  File "mpi4py/MPI/Comm.pyx", line 690, in mpi4py.MPI.Comm.Bcast
  File "mpi4py/MPI/msgbuffer.pxi", line 531, in mpi4py.MPI._p_msg_cco.for_bcast
  File "mpi4py/MPI/msgbuffer.pxi", line 495, in mpi4py.MPI._p_msg_cco.for_cco_send
  File "mpi4py/MPI/msgbuffer.pxi", line 203, in mpi4py.MPI.message_simple
  File "mpi4py/MPI/msgbuffer.pxi", line 138, in mpi4py.MPI.message_basic
  File "mpi4py/MPI/asbuffer.pxi", line 365, in mpi4py.MPI.getbuffer
  File "mpi4py/MPI/asbuffer.pxi", line 144, in mpi4py.MPI.PyMPI_GetBuffer
  File "mpi4py/MPI/asbuffer.pxi", line 142, in mpi4py.MPI.PyMPI_GetBuffer
  File "mpi4py/MPI/asdlpack.pxi", line 204, in mpi4py.MPI.Py_GetDLPackBuffer
  File "mpi4py/MPI/asdlpack.pxi", line 105, in mpi4py.MPI.dlpack_check_contig
BufferError: dlpack: buffer is not contiguous
```

I don't know too much about the DLPack interface, but I can't detect anything wrong with this logic here https://github.com/mpi4py/mpi4py/blob/cb2f64052c91e66708bc49e822acfc405ef3e01a/src/mpi4py/MPI/asdlpack.pxi#L79-L84 and the values of `.stride()` and `.shape` in PyTorch's interface haven't changed, although I'm not sure that is the same as the dlpack `strides` and `shape`.

**Comment by leofang** [comment]
I seem to recall the size-1 reduction issue has been fixed (https://github.com/mpi4py/mpi4py/issues/238), maybe @dalcinl can correct me, but could you try building mpi4py from the master branch?

**Comment by jmerizia** [comment]
Wow that was quick! I actually just realized I was not on master, and saw the fix PR. master branch should do the trick. Thanks!

**Comment by dalcinl** [comment]
I'm about to release v3.1.4, it will contain a fix for this issue.
