### ISSUE TITLE
How to run multi node task with Spawn?

### ISSUE THREAD

**Issue by ZZWHU** [mpi4py/mpi4py#392]
For some reason, I have to use python3 to run LLM with tensor parallelism and parallel parallelism, and cannot use mpirun.
So I use `mpi4py.MPI.Spwan`， it works well in single node, but I don't know how to set MPI.Info for Multi-node.
Here is my code (single node):
```python
from mpi4py import MPI
comm = MPI.COMM_WORLD
new_comm = comm.Spawn(command="python3", 
                      args=["llama.py"],
                      maxprocs=2)
```  

Here is my code (Multi node):
```python
from mpi4py import MPI
comm = MPI.COMM_WORLD
info = MPI.Info.Create()
# info.Set('add-hostfile', 'worker_hosts')
info.Set('host', 'c4,slurmctld1')
new_comm = comm.Spawn(command="python3", 
                      args=["llama.py"],
                      maxprocs=2
                     info=info)
``` 
And get the error:
```
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 1
slots that were requested by the application:

  python3

Either request fewer slots for your application, or make more slots
available for use.

A "slot" is the Open MPI term for an allocatable unit where we can
launch a process.  The number of slots available are defined by the
environment in which Open MPI processes are run:

  1. Hostfile, via "slots=N" clauses (N defaults to number of
     processor cores if not provided)
  2. The --host command line parameter, via a ":N" suffix on the
     hostname (N defaults to 1 if not provided)
  3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
  4. If none of a hostfile, the --host command line parameter, or an
     RM is present, Open MPI defaults to the number of processor cores

In all the above cases, if you want Open MPI to default to the number
of hardware threads instead of the number of processor cores, use the
--use-hwthread-cpus option.

Alternatively, you can use the --oversubscribe option to ignore the
number of available slots when deciding the number of processes to
launch.
--------------------------------------------------------------------------
[2023-08-30 10:41:30,687] ERROR in app: Exception on /init_model [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "../examples/pytorch/llama/app.py", line 26, in init_model
    new_comm = comm.Spawn(command="python3",
  File "mpi4py/MPI/Comm.pyx", line 1931, in mpi4py.MPI.Intracomm.Spawn
mpi4py.MPI.Exception: MPI_ERR_SPAWN: could not spawn processes
```

**Comment by ZZWHU** [comment]
```python
from mpi4py import MPI
comm = MPI.COMM_WORLD
info = MPI.Info.Create()
info.Set('hosts', 'c4,slurmctld1')
new_comm = comm.Spawn(command="python3", 
                      args=["llama.py"],
                      maxprocs=2
                     info=info)
``` 
I use `hosts`  instead of `host`, the code can run, but all processes are on the single node instead of one for each node.

**Comment by dalcinl** [comment]
Looks like you are using Open MPI. You should read their documentation, or ask them about how to use the library. I'm not quite sure what did you mean by: _For some reason, ..., and cannot use mpirun_.

**Comment by dalcinl** [comment]
@ZZWHU Any updates from your side? Could you figure out what's going on?

**Comment by dalcinl** [comment]
Closing as the OP is unresponsive.
