### ISSUE TITLE
Error when running `osu_lantency` under a large data size

### ISSUE THREAD

**Issue by zhuo121** [mpi4py/mpi4py#575]
## Description
I tried to run `demo/osu_latency` on two gpu nodes. The original file works fine, but when I change the amount of data transferred to 4GB, the program reports an error.
```
Traceback (most recent call last):
  File "/home/mpi/mpi_programme/osu_latency.py", line 77, in <module>
    osu_latency()
  File "/home/mpi/mpi_programme/osu_latency.py", line 50, in osu_latency
    comm.Send(s_msg, 1, 1)
  File "mpi4py/MPI/Comm.pyx", line 280, in mpi4py.MPI.Comm.Send
  File "mpi4py/MPI/msgbuffer.pxi", line 455, in mpi4py.MPI.message_p2p_send
  File "mpi4py/MPI/msgbuffer.pxi", line 438, in mpi4py.MPI._p_msg_p2p.for_send
  File "mpi4py/MPI/msgbuffer.pxi", line 230, in mpi4py.MPI.message_simple
OverflowError: value too large to convert to int
Traceback (most recent call last):
  File "/home/mpi/mpi_programme/osu_latency.py", line 77, in <module>
    osu_latency()
  File "/home/mpi/mpi_programme/osu_latency.py", line 55, in osu_latency
    comm.Recv(r_msg, 0, 1)
  File "mpi4py/MPI/Comm.pyx", line 297, in mpi4py.MPI.Comm.Recv
  File "mpi4py/MPI/msgbuffer.pxi", line 460, in mpi4py.MPI.message_p2p_recv
  File "mpi4py/MPI/msgbuffer.pxi", line 446, in mpi4py.MPI._p_msg_p2p.for_recv
  File "mpi4py/MPI/msgbuffer.pxi", line 230, in mpi4py.MPI.message_simple
OverflowError: value too large to convert to int
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[31380,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```
**This seems to be a problem with the type of parameter `buf` in `comm.Send()`. I've tried transferring a 4GB buffer `s_buf` directly instead of `[s_buf, size, MPI.BYTE]` and it could send properly. So, can you fix this error?** 

## Environment
cuda 12.4
openmpi 4.1.6
mpi4py 3.1.6

## Details
The `# change` parts are my changes to the original file:
```
from mpi4py import MPI

def osu_latency(
    BENCHMARH = "MPI Latency Test",
    skip = 10,                                                         # change 
    loop = 100,                                                      # change 
    skip_large = 1,                                                  # change 
    loop_large = 1,                                                    # change 
    large_message_size = 8192,
    MAX_MSG_SIZE = 1<<32,                                            # change 
    ):

    comm = MPI.COMM_WORLD
    myid = comm.Get_rank()
    numprocs = comm.Get_size()

    if numprocs != 2:
        if myid == 0:
            errmsg = "This test requires exactly two processes"
        else:
            errmsg = None
        raise SystemExit(errmsg)

    s_buf = allocate(MAX_MSG_SIZE)
    r_buf = allocate(MAX_MSG_SIZE)

    if myid == 0:
        print (f'# {BENCHMARH}')
    if myid == 0:
        print ('# %-8s%20s' % ("Size [B]", "Latency [us]"))

    message_sizes = [0] + [2**i for i in range(40)]                    #change
    for size in message_sizes:
        if size > MAX_MSG_SIZE:
            break
        if size > large_message_size:
            skip = skip_large
            loop = loop_large
        iterations = list(range(loop+skip))
        s_msg = [s_buf, size, MPI.BYTE]
        r_msg = [r_buf, size, MPI.BYTE]
        #
        comm.Barrier()
        if myid == 0:
            for i in iterations:
                if i == skip:
                    t_start = MPI.Wtime()
                comm.Send(s_msg, 1, 1)
                comm.Recv(r_msg, 1, 1)
            t_end = MPI.Wtime()
        elif myid == 1:
            for i in iterations:
                comm.Recv(r_msg, 0, 1)
                comm.Send(s_msg, 0, 1)
        #
        if myid == 0:
            latency = (t_end - t_start) * 1e6 / (2 * loop)
            print ('%-10d%20.2f' % (size, latency))


def allocate(n):
    try:
        import mmap
        return mmap.mmap(-1, n)
    except (ImportError, OSError):
        try:
            from numpy import zeros
            return zeros(n, 'B')
        except ImportError:
            from array import array
            return array('B', [0]) * n


if __name__ == '__main__':
    osu_latency()
```

**Comment by dalcinl** [comment]
If you are not using an MPI 4.x implementation, then the maximum size you can communicate is 2 GB (actually 2 G datatype entries). This is a well known limitation of the MPI standard up to version 3.1. One possible way to workaround the issue is to create a user-defined `MPI.Datatype`. Google for BigMPI to learn more. mpi4py has some support for creating these datatypes.

You should try to adapt the code the following way.

```python
from mpi4py.util.pkl5 import _BigMPI as BigMPI
bigmpi = BigMPI()
...
for _ in ...:
    bigbuf = bigmpi(buf) # returns a tuple (buf, 1, bigdatatype)
    MPI.Send(bigbuf, ...)
...
with bigmpi: pass # to clear the big Datatype cache
```

**Comment by zhuo121** [comment]
**I think this should not be an error due to the MPI version, as I'm using openmpi 4.1.6, and I can run the code below correctly.** 
```
# A code to measure the latency between two gpus

from mpi4py import MPI
import cupy

def p2p_gpu_latency(
    BENCHMARH = "MPI Latency Test",
    skip = 0,
    loop = 1,
    large_message_size = 1048576,
    MAX_MSG_SIZE = 1<<32,
    ):

    comm = MPI.COMM_WORLD
    myid = comm.Get_rank()
    numprocs = comm.Get_size()

    if numprocs != 2:
        if myid == 0:
            errmsg = "This test requires exactly two processes"
        else:
            errmsg = None
        raise SystemExit(errmsg)

    # Define 4GB buffer
    s_buf = cupy.arange((MAX_MSG_SIZE / 4), dtype='i')
    r_buf = cupy.empty_like(s_buf)

    if myid == 0:
        print (f'# {BENCHMARH}')
    if myid == 0:
        print ('# %-8s%20s%20s' % ("Size [B]", "Latency [us]", "Bandwidth [GB/s]"))

    cupy.cuda.get_current_stream().synchronize()
    iterations = list(range(loop+skip))

    # Transmit the 4GB buffer directly, not define the size of buffer
    s_msg = s_buf
    r_msg = r_buf
    # s_msg = [s_buf, MAX_MSG_SIZE, MPI.BYTE]
    # r_msg = [r_buf, MAX_MSG_SIZE, MPI.BYTE]
    #
    comm.Barrier()
    if myid == 0:
        for i in iterations:
            if i == skip:
                t_start = MPI.Wtime()
            comm.Send(s_msg, 1, 1)
            comm.Recv(r_msg, 1, 1)
        t_end = MPI.Wtime()
    elif myid == 1:
        for i in iterations:
            comm.Recv(r_msg, 0, 1)
            comm.Send(s_msg, 0, 1)
    #
    if myid == 0:
        latency = (t_end - t_start) * 1e6 / (2 * loop)
        bandwidth = MAX_MSG_SIZE / (1<<30) / (t_end - t_start) * (2 * loop)
        print ('%-10d%20.2f%20.3f' % (MAX_MSG_SIZE, latency, bandwidth))


if __name__ == '__main__':
    p2p_gpu_latency()
```
**The code transmit the 4GB buffer directly through `s_msg = s_buf, comm.Send(s_msg, 1, 1)`. The result is**
```
[1730803096.352619] [gpu2:3662453:0]     ucp_context.c:1234 UCX  WARN  network device 'ens9f0' is not available, please use one or more of: 'eno8303'(tcp), 'enp152s0f1'(tcp), 'enp75s0f0np0'(tcp), 'idrac'(tcp), 'lo'(tcp)
[1730803096.353272] [gpu1:1960880:0]     ucp_context.c:1234 UCX  WARN  network device 'enp75s0f0np0' is not available, please use one or more of: 'eno2'(tcp), 'ens16f0'(tcp), 'ens9f0'(tcp), 'lo'(tcp)
# MPI Latency Test
# Size [B]        Latency [us]    Bandwidth [GB/s]
4294967296         56636599.29               0.071
```
**However, when I want to further define the size of buffer use as `s_msg = [s_buf,  MAX_MSG_SIZE, MPI.BYTE], comm.Send(s_msg, 1, 1)`, The error happens.**
```
[1730803394.573137] [gpu2:3663906:0]     ucp_context.c:1234 UCX  WARN  network device 'ens9f0' is not available, please use one or more of: 'eno8303'(tcp), 'enp152s0f1'(tcp), 'enp75s0f0np0'(tcp), 'idrac'(tcp), 'lo'(tcp)
[1730803394.546266] [gpu1:1961037:0]     ucp_context.c:1234 UCX  WARN  network device 'enp75s0f0np0' is not available, please use one or more of: 'eno2'(tcp), 'ens16f0'(tcp), 'ens9f0'(tcp), 'lo'(tcp)
# MPI Latency Test
# Size [B]        Latency [us]    Bandwidth [GB/s]
Traceback (most recent call last):
  File "/home/mpi/mpi_programme/large_p2p_gpu.py", line 60, in <module>
    p2p_gpu_latency()
  File "/home/mpi/mpi_programme/large_p2p_gpu.py", line 45, in p2p_gpu_latency
    comm.Send(s_msg, 1, 1)
  File "mpi4py/MPI/Comm.pyx", line 280, in mpi4py.MPI.Comm.Send
  File "mpi4py/MPI/msgbuffer.pxi", line 455, in mpi4py.MPI.message_p2p_send
  File "mpi4py/MPI/msgbuffer.pxi", line 438, in mpi4py.MPI._p_msg_p2p.for_send
  File "mpi4py/MPI/msgbuffer.pxi", line 230, in mpi4py.MPI.message_simple
OverflowError: value too large to convert to int
Traceback (most recent call last):
  File "/home/mpi/mpi_programme/large_p2p_gpu.py", line 60, in <module>
    p2p_gpu_latency()
  File "/home/mpi/mpi_programme/large_p2p_gpu.py", line 50, in p2p_gpu_latency
    comm.Recv(r_msg, 0, 1)
  File "mpi4py/MPI/Comm.pyx", line 297, in mpi4py.MPI.Comm.Recv
  File "mpi4py/MPI/msgbuffer.pxi", line 460, in mpi4py.MPI.message_p2p_recv
  File "mpi4py/MPI/msgbuffer.pxi", line 446, in mpi4py.MPI._p_msg_p2p.for_recv
  File "mpi4py/MPI/msgbuffer.pxi", line 230, in mpi4py.MPI.message_simple
OverflowError: value too large to convert to int
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[41383,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```
**So actually, MPI allows me to transmit 4GB data, it's just that when I'm stating how much data to transmit in the buffer, it generates an error. However, when I was testing, I couldn't reopen a buffer for each transmission, and the best way to do it was to open a large enough buffer and then specify the size of the amount of data to be transmitted.**
**Furthermore, when I was testing, I found 1GB size can transmit, but 2GB and 4GB cannot.**

**Comment by zhuo121** [comment]
Thank for your reply and you‘re right,` (1<<31)-1` entries success and `1<<31` entries fail(not Bytes). In fact, I just want to make sure that the Bytes of data transferred is 4GB.  So if I transmit `1<<30` `int32`,  it should be theoretically feasible and happen to be 4GB?
This is actually what I'm trying to achieve in the code, but I still don't understand why it's reporting an error.

**Comment by zhuo121** [comment]
Oh, I think I know why there is an error. I didn't realise before that `[s_buf, MAX_MSG_SIZE, MPI.BYTE]` will read memory as `Byte` instead of `int`! So, actually, although I have `1<<30` `int`, mpi4py transmit it as `1<<32` `Byte`. When I use  `[s_buf, MAX_MSG_SIZE, MPI.INT]` instead , the code goes right.

**Comment by zhuo121** [comment]
Thank you so much for your patience.  Now the problem is solved.

**Comment by dalcinl** [comment]
> `[s_buf, MAX_MSG_SIZE, MPI.BYTE]` will read memory as `Byte` instead of `int`!

Indeed! When you specify a message count and/or datatype as 3-list/tuple, mpi4py will trust and obey you and ignore the array size/datatype without even a warning.
