### ISSUE TITLE
TestUtilDTLib fails on s390x: incorrect long double alignment

### ISSUE THREAD

**Issue by drew-parsons** [mpi4py/mpi4py#91]
We discussed at https://github.com/mpi4py/mpi4py/issues/80#issuecomment-902349139 a test failure on s390x architecture:
```
FAIL: testStruct4 (test_util_dtlib.TestUtilDTLib) (typecode='g')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/test/test_util_dtlib.py", line 165, in testStruct4
    self.assertEqual(mt.extent, n*ex1)
AssertionError: 40 != 48

======================================================================
FAIL: testStruct4 (test_util_dtlib.TestUtilDTLib) (typecode='G')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/test/test_util_dtlib.py", line 165, in testStruct4
    self.assertEqual(mt.extent, n*ex1)
AssertionError: 72 != 80
```

Tests on s390x showed this:
```
#include <stddef.h>
#include <stdio.h>

typedef struct {char a; long double b; char c;} s;

int main() { 
  printf("long double has alignment %d\n", offsetof(s,b));
  printf("long double has size %d\n", sizeof(long double));
  printf("stuct s has size %d\n", sizeof(s));
}
```
gives
```
$ ./mtest2
long double has alignment 8
long double has size 16
stuct s has size 32
```

In python,
```
# import numpy as np                                                                                                                    
# print(np.dtype('c,g,c', align=True))
{'names':['f0','f1','f2'], 'formats':['S1','>f16','S1'], 'offsets':[0,8,24], 'itemsize':32, 'aligned':True}
```

and also in python,
```
from ctypes import *

class S(Structure):
    _fields_ = [
        ("a", c_char),
        ("b", c_longdouble),
        ("c", c_char),
    ]

print(sizeof(S))
```
returns 32.

The alignment of long double on s390x is not the same as that expected by mpi4py as found on other architectures.

**Comment by dalcinl** [comment]
@drew-parsons Can you please try patching with #92?

**Comment by drew-parsons** [comment]
It's now failing at l.168 `self.assertTrue(dt.isalignedstruct)`

**Comment by drew-parsons** [comment]
s390x now passes tests successfully with the updated PR #92 ,
https://buildd.debian.org/status/fetch.php?pkg=mpi4py&arch=s390x&ver=3.1.1-4&stamp=1631618262&raw=0
